<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator._JlOT3n' shared service.

return $this->privates['.service_locator._JlOT3n'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\WildController::showByCategory' => ['privates', '.service_locator.gEKwHLd', 'get_ServiceLocator_GEKwHLdService.php', true],
    'App\\Controller\\WildController::showByEpisode' => ['privates', '.service_locator.qNhmoAu', 'get_ServiceLocator_QNhmoAuService.php', true],
    'App\\Controller\\WildController::showByProgram' => ['privates', '.service_locator.yrDeEqb', 'get_ServiceLocator_YrDeEqbService.php', true],
    'App\\Controller\\WildController::showBySeason' => ['privates', '.service_locator.X1wF8Wb', 'get_ServiceLocator_X1wF8WbService.php', true],
    'App\\Controller\\WildController:showByCategory' => ['privates', '.service_locator.gEKwHLd', 'get_ServiceLocator_GEKwHLdService.php', true],
    'App\\Controller\\WildController:showByEpisode' => ['privates', '.service_locator.qNhmoAu', 'get_ServiceLocator_QNhmoAuService.php', true],
    'App\\Controller\\WildController:showByProgram' => ['privates', '.service_locator.yrDeEqb', 'get_ServiceLocator_YrDeEqbService.php', true],
    'App\\Controller\\WildController:showBySeason' => ['privates', '.service_locator.X1wF8Wb', 'get_ServiceLocator_X1wF8WbService.php', true],
], [
    'App\\Controller\\WildController::showByCategory' => '?',
    'App\\Controller\\WildController::showByEpisode' => '?',
    'App\\Controller\\WildController::showByProgram' => '?',
    'App\\Controller\\WildController::showBySeason' => '?',
    'App\\Controller\\WildController:showByCategory' => '?',
    'App\\Controller\\WildController:showByEpisode' => '?',
    'App\\Controller\\WildController:showByProgram' => '?',
    'App\\Controller\\WildController:showBySeason' => '?',
]);
