<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Q5DEgz5' shared service.

return $this->privates['.service_locator.Q5DEgz5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\ProgramController::delete' => ['privates', '.service_locator.tXoa_ER', 'get_ServiceLocator_TXoaERService.php', true],
    'App\\Controller\\ProgramController::edit' => ['privates', '.service_locator.tXoa_ER', 'get_ServiceLocator_TXoaERService.php', true],
    'App\\Controller\\ProgramController::index' => ['privates', '.service_locator.58Rml10', 'get_ServiceLocator_58Rml10Service.php', true],
    'App\\Controller\\ProgramController::show' => ['privates', '.service_locator.tXoa_ER', 'get_ServiceLocator_TXoaERService.php', true],
    'App\\Controller\\SeasonController::delete' => ['privates', '.service_locator.ADeF0mv', 'get_ServiceLocator_ADeF0mvService.php', true],
    'App\\Controller\\SeasonController::edit' => ['privates', '.service_locator.ADeF0mv', 'get_ServiceLocator_ADeF0mvService.php', true],
    'App\\Controller\\SeasonController::index' => ['privates', '.service_locator.RILWcPl', 'get_ServiceLocator_RILWcPlService.php', true],
    'App\\Controller\\SeasonController::show' => ['privates', '.service_locator.ADeF0mv', 'get_ServiceLocator_ADeF0mvService.php', true],
    'App\\Controller\\WildController::showByCategory' => ['privates', '.service_locator.gEKwHLd', 'get_ServiceLocator_GEKwHLdService.php', true],
    'App\\Controller\\WildController::showByEpisode' => ['privates', '.service_locator.qNhmoAu', 'get_ServiceLocator_QNhmoAuService.php', true],
    'App\\Controller\\WildController::showByProgram' => ['privates', '.service_locator.yrDeEqb', 'get_ServiceLocator_YrDeEqbService.php', true],
    'App\\Controller\\WildController::showBySeason' => ['privates', '.service_locator.X1wF8Wb', 'get_ServiceLocator_X1wF8WbService.php', true],
    'App\\Controller\\ProgramController:delete' => ['privates', '.service_locator.tXoa_ER', 'get_ServiceLocator_TXoaERService.php', true],
    'App\\Controller\\ProgramController:edit' => ['privates', '.service_locator.tXoa_ER', 'get_ServiceLocator_TXoaERService.php', true],
    'App\\Controller\\ProgramController:index' => ['privates', '.service_locator.58Rml10', 'get_ServiceLocator_58Rml10Service.php', true],
    'App\\Controller\\ProgramController:show' => ['privates', '.service_locator.tXoa_ER', 'get_ServiceLocator_TXoaERService.php', true],
    'App\\Controller\\SeasonController:delete' => ['privates', '.service_locator.ADeF0mv', 'get_ServiceLocator_ADeF0mvService.php', true],
    'App\\Controller\\SeasonController:edit' => ['privates', '.service_locator.ADeF0mv', 'get_ServiceLocator_ADeF0mvService.php', true],
    'App\\Controller\\SeasonController:index' => ['privates', '.service_locator.RILWcPl', 'get_ServiceLocator_RILWcPlService.php', true],
    'App\\Controller\\SeasonController:show' => ['privates', '.service_locator.ADeF0mv', 'get_ServiceLocator_ADeF0mvService.php', true],
    'App\\Controller\\WildController:showByCategory' => ['privates', '.service_locator.gEKwHLd', 'get_ServiceLocator_GEKwHLdService.php', true],
    'App\\Controller\\WildController:showByEpisode' => ['privates', '.service_locator.qNhmoAu', 'get_ServiceLocator_QNhmoAuService.php', true],
    'App\\Controller\\WildController:showByProgram' => ['privates', '.service_locator.yrDeEqb', 'get_ServiceLocator_YrDeEqbService.php', true],
    'App\\Controller\\WildController:showBySeason' => ['privates', '.service_locator.X1wF8Wb', 'get_ServiceLocator_X1wF8WbService.php', true],
], [
    'App\\Controller\\ProgramController::delete' => '?',
    'App\\Controller\\ProgramController::edit' => '?',
    'App\\Controller\\ProgramController::index' => '?',
    'App\\Controller\\ProgramController::show' => '?',
    'App\\Controller\\SeasonController::delete' => '?',
    'App\\Controller\\SeasonController::edit' => '?',
    'App\\Controller\\SeasonController::index' => '?',
    'App\\Controller\\SeasonController::show' => '?',
    'App\\Controller\\WildController::showByCategory' => '?',
    'App\\Controller\\WildController::showByEpisode' => '?',
    'App\\Controller\\WildController::showByProgram' => '?',
    'App\\Controller\\WildController::showBySeason' => '?',
    'App\\Controller\\ProgramController:delete' => '?',
    'App\\Controller\\ProgramController:edit' => '?',
    'App\\Controller\\ProgramController:index' => '?',
    'App\\Controller\\ProgramController:show' => '?',
    'App\\Controller\\SeasonController:delete' => '?',
    'App\\Controller\\SeasonController:edit' => '?',
    'App\\Controller\\SeasonController:index' => '?',
    'App\\Controller\\SeasonController:show' => '?',
    'App\\Controller\\WildController:showByCategory' => '?',
    'App\\Controller\\WildController:showByEpisode' => '?',
    'App\\Controller\\WildController:showByProgram' => '?',
    'App\\Controller\\WildController:showBySeason' => '?',
]);
