<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBJEqsXj\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBJEqsXj/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBJEqsXj.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBJEqsXj\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerBJEqsXj\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'BJEqsXj',
    'container.build_id' => '37244259',
    'container.build_time' => 1575383454,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBJEqsXj');
