<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRrXZkrM\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRrXZkrM/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRrXZkrM.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRrXZkrM\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerRrXZkrM\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'RrXZkrM',
    'container.build_id' => '5b72e069',
    'container.build_time' => 1576140638,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRrXZkrM');
