<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSmxx8C9\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSmxx8C9/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSmxx8C9.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSmxx8C9\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSmxx8C9\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Smxx8C9',
    'container.build_id' => '704595ff',
    'container.build_time' => 1576231646,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSmxx8C9');
